### ISSUE TITLE
 Unable to find module with ID: aurelia-plugins-google-maps/aurelia-plugins-google-maps-element

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia-plugins/aurelia-plugins-google-maps#2]
Hi,

When I tried this plugin with webpack, I experienced the error in the title. 

PLATFORM.moduleName() is needed. I'm not sure it is needed with other loaders, maybe PLATFORM.moduleName() takes care the difference.

in main.ts:

```
import { PLATFORM } from 'aurelia-pal';
...
        .plugin(PLATFORM.moduleName('aurelia-plugins-google-maps'), config => {
```

in aurelia-plugins-google-maps.js:

```
import { PLATFORM } from 'aurelia-pal';
...

  aurelia.globalResources(PLATFORM.moduleName('./aurelia-plugins-google-maps-element'));
```

**Comment by bartlenaerts** [comment]
Hi,
this is fixed in the new version v2.3.0.
